#!/bin/bash
#
# weekly-update.sh — 每周五中午自动更新 awesome-algorithm-auto-tools
#
# 使用本地 Claude Code（用你的订阅额度，不需要 API key）
# 流程：搜索最新工具 → 更新文档 → 提交 → 推送 → 创建 PR
#
# 用法:
#   ./scripts/weekly-update.sh          # 正常执行
#   ./scripts/weekly-update.sh --dry-run # 只搜索，不提交不推送
#
# 设置定时任务（二选一）:
#   方式 1: crontab -e 然后添加:
#     0 12 * * 5 cd /Users/bin/Desktop/project/AfterPho/newRD/awesome-algorithm-auto-tools && ./scripts/weekly-update.sh >> scripts/update.log 2>&1
#
#   方式 2: 在 Claude Code 中运行:
#     /schedule 命令设置

set -euo pipefail

# ── 配置 ──────────────────────────────────────────────
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PROMPT_FILE="$PROJECT_DIR/.github/prompts/weekly-update.md"
LOG_DIR="$PROJECT_DIR/scripts"
DATE=$(date +%Y-%m-%d)
BRANCH="auto-update/${DATE}"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
    echo "[$DATE] Dry-run mode: will search but not commit/push"
fi

# ── 日志 ──────────────────────────────────────────────
log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

# ── 前置检查 ──────────────────────────────────────────
log "Starting weekly update..."
cd "$PROJECT_DIR"

if ! command -v claude &>/dev/null; then
    log "ERROR: claude CLI not found. Install: npm i -g @anthropic-ai/claude-code"
    exit 1
fi

if ! command -v gh &>/dev/null; then
    log "ERROR: gh CLI not found. Install: brew install gh"
    exit 1
fi

# 确保在 main 分支且代码最新
log "Syncing main branch..."
git checkout main
git pull origin main

# 创建更新分支
log "Creating branch: $BRANCH"
git checkout -b "$BRANCH"

# ── 执行 Claude Code 更新 ────────────────────────────
log "Running Claude Code to search for new tools..."
PROMPT=$(cat "$PROMPT_FILE")

claude -p "$PROMPT" \
    --max-turns 30 \
    --allowedTools "WebSearch,Read,Edit,Write,Glob,Grep,Bash(git diff*),Bash(git status*),Bash(wc *)" \
    2>&1 | tee "$LOG_DIR/last-run-${DATE}.log"

# ── 检查是否有变更 ───────────────────────────────────
if git diff --quiet && git diff --cached --quiet; then
    log "No new tools found this week. Cleaning up."
    git checkout main
    git branch -D "$BRANCH"
    echo "$DATE: No new tools found." >> "$LOG_DIR/history.log"
    exit 0
fi

log "Changes detected:"
git diff --stat

if $DRY_RUN; then
    log "Dry-run complete. Discarding changes."
    git checkout -- .
    git checkout main
    git branch -D "$BRANCH"
    exit 0
fi

# ── 提交 + 推送 + 创建 PR ────────────────────────────
log "Committing changes..."
git add README.md "算法自动化训练.md"
git commit -m "$(cat <<EOF
Auto-update: add new tools (${DATE})

Weekly automated scan for new algorithm automation tools.

Co-Authored-By: Claude <noreply@anthropic.com>
EOF
)"

log "Pushing to origin..."
git push -u origin "$BRANCH"

log "Creating PR..."
PR_URL=$(gh pr create \
    --title "Weekly update: new tools (${DATE})" \
    --body "$(cat <<'PREOF'
## Summary

Automated weekly scan for new algorithm automation tools.

Generated by local Claude Code via `scripts/weekly-update.sh`.

## Review Checklist

- [ ] New entries are accurate and links work
- [ ] Table formatting is correct in README.md
- [ ] Chinese descriptions are appropriate
- [ ] No existing entries were removed

---
🤖 Auto-generated by weekly-update.sh + Claude Code
PREOF
)" \
    --base main \
    --head "$BRANCH")

log "PR created: $PR_URL"
echo "$DATE: PR created - $PR_URL" >> "$LOG_DIR/history.log"

# 回到 main 分支
git checkout main

log "Done!"
